version: '3.3'
services:

    nginx:
        image: nginx
        ports:
            - "8088:80"
        depends_on:
            - php
        volumes:
            - .:/app:ro
            - ./dev/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro

    php:
        build: dev/php
        volumes:
            - .:/app:cached
            - ./var:/app/var:delegated
            - ./vendor:/app/vendor:delegated
            - ./public/node_modules:/app/public/node_modules:ro
        depends_on:
            - db


    db:
        image: postgres
        restart: always
        ports:
          - "5542:5432"
        environment:
            POSTGRES_PASSWORD: root

    encore:
        image: node:10-alpine
        volumes:
            - .:/app
        ports:
            - "${DEV_SERVER_PORT:-8889}:8080"
        working_dir: /app
        command: ["yarn", "--host=0.0.0.0"]

    maildev:
        image: djfarrelly/maildev
        ports:
            - "8089:80"
